### ISSUE TITLE
Add warnings for not supported nodeJS version

### ISSUE THREAD

**Issue by BashCloud** [lightvue/lightvue#109]
### Description:
Current document is designed to work for nodeJS version upto 14.

### Proposed solution:
Add warnings during installation itself. IT can be configured within package.json file.

**Comment by hrushi-thorat** [comment]
@BashCloud  I created a PR for this issue: https://github.com/lightvue/lightvue/pull/115 .

**Comment by BashCloud** [comment]
Thanks @hrushi-thorat .
