### ISSUE TITLE
Rating component showRating props not working properly

### ISSUE THREAD

**Issue by itsekta** [lightvue/lightvue#126]
### Relevant Component(s):
1. [Rating](https://lightvue.org/vue-components/rating)

### Description:
When <b>showRating</b> prop is true the rating works properly but when it is false then it makes the whole rating element disabled instead of  hiding the rating value(selected stars value)

### Proposed Solution:
Check the <b>if condition</b> used to show rating value when showRating prop is true.

### Additional Info:
![Rating_Docs___LightVue_-_Google_Chrome_2022-09-30_17-46-49_AdobeExpress (1)](https://user-images.githubusercontent.com/60789158/193292601-9be5065c-0a40-4df3-843e-3f999b1aefbd.gif)

**Comment by RoshanShrestha123** [comment]
Hey @itsekta, new to open source contributions here.
Just wanted to know few things.

If the Rating is set to Show Rating -> false, it will hide the value of the rating (empty rating view).
Or do want to completely hide the component itself?

(On first case), if i am just hiding the rating instead, that means its disabled as well?
view will be something like this?
![image](https://user-images.githubusercontent.com/31877486/193397351-aa5a7507-f04e-4352-8c33-535e9dcc01e5.png)

And would love to work on this, thanks

**Comment by itsekta** [comment]
> 

Hi! @RoshanShrestha123 
If the showRating prop is set to false it should hide the the rating only(the value like 3.5) which is showing when the value is true.
And if we are setting the showRating prop to false it shouldn't disable the rating element.

**Comment by RoshanShrestha123** [comment]
Gotcha!
Can you assign me this one?

**Comment by itsekta** [comment]
For any further assistance you can join our slack channel https://join.slack.com/t/slack-qgs9925/shared_invite/zt-1g6falep2-9v3887ttNrjrcPdxi1if_A

**Comment by RoshanShrestha123** [comment]
Thanks @itsekta
