### ISSUE TITLE
Add LvColorPicker component in LvSlider component's Realtime Customizations

### ISSUE THREAD

**Issue by itsekta** [lightvue/lightvue#137]
### Relevant Component(s):
1. LvSlider(https://lightvue.org/vue-components/slider) --- sliderColor
2. LvSlider(https://lightvue.org/vue-components/slider) --- trackColor

### Description:
Currently, we don't have a color pallet to set the color of the trackColor and sliderColor in LvSlider's Realtime Customizations.
Add LvColorPicker component in LvSlider component's Realtime Customizations similar to LvRating Component's Realtime Customizations.

### Proposed Solution:
Use **lv-color picker** component in the **sliderBestDemo** instead of lv-input.
Check **RatingBestDemo** for reference.

### Currently in Slider Component
![image](https://user-images.githubusercontent.com/60789158/193420743-7d8e2e27-eb3a-4472-9067-14d97f385265.png)

### In Rating Component
![image](https://user-images.githubusercontent.com/60789158/193420730-57b35c7b-041b-49af-a503-71b64dbfce97.png)

**Comment by alexjharrison** [comment]
I'd like to be assigned this issue. Thanks!

**Comment by itsekta** [comment]
Sure @alexjharrison

**Comment by itsekta** [comment]
@alexjharrison For any query you can join our slack channel https://join.slack.com/t/slack-qgs9925/shared_invite/zt-1g6falep2-9v3887ttNrjrcPdxi1if_A
