### ISSUE TITLE
Implement recommended community standards to the project

### ISSUE THREAD

**Issue by orama254** [lightvue/lightvue#148]
Hello Team, 

I was going though this project and noticed that there are some missing items based on the [Github Community Standards recommendations](https://github.com/lightvue/lightvue/community) that would make the project contributor friendly, e.g. a code of conduct, a license and a pull request template.

Let me know if this is something you would like to implement on this project.

**Comment by hrushi-thorat** [comment]
Hello @orama254 . We appreciate your interest in contributing to lightvue! You can proceed with the code of conduct and pull request template. For further assistance you can join our [Slack community](https://join.slack.com/t/slack-qgs9925/shared_invite/zt-1g6falep2-9v3887ttNrjrcPdxi1if_A).
