### ISSUE TITLE
Fix All rights reserved convention

### ISSUE THREAD

**Issue by mohit2314** [lightvue/lightvue#160]
### Relevant Component(s):
1. Landing page

### Description:
Currently the convention followed is not correct

### Proposed Solution:
Can refer to attached image for possible solution.

Current Convention
![image](https://user-images.githubusercontent.com/24897097/197743901-cdddc92a-67e8-4cae-878b-9de20b15b912.png)

Correct Convention
![image](https://user-images.githubusercontent.com/24897097/197743769-9791cdad-3ace-4107-ae1a-3f3be43207db.png)

**Comment by javamultiplex** [comment]
@mohit2314  - I would like to work on this, can you please assign to me?

**Comment by Armaan2807** [comment]
Please assign it to me

**Comment by mohit2314** [comment]
> Please assign it to me

Sure
