### ISSUE TITLE
Add light-scrollbar class to Textarea

### ISSUE THREAD

**Issue by roch25** [lightvue/lightvue#32]
### Relevant Component(s):
1. [LvTextarea](https://lightvue.org/vue-components/textarea)

### Description:
When LvTextarea has autoResize off, if it overflows, the browser's default scrollbar appears.

### Proposed Solution:
Add the `light-scrollbar` class to the textarea element so that LightVue's custom scrollbar appears.

### Impact Area:
- [x] Component Core

**Comment by parzival272000** [comment]
Can i take this up??

**Comment by roch25** [comment]
Yes, go ahead @parzival272000
